name: Generate ASCII Artwork
on:
    push
#each job need to run on it's own machine, jobs run in parallel (default)
#we want to increment them build then test then deploy 
#so we use needs syntax.
#each job runs on a seperate machine so files aren't shared across them
#we need to share the files using (storing workflow data as artifacts)
#==> install upload a build artifact, download a single artifact from marketplace

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
       - name: install cowsay program
         run: sudo apt-get install cowsay -y

       - name: execute cowsay CMD
         run: cowsay -f dragon "Run for cover, I am a DRAGON ... RAWR" >> dragon.txt

       - name: Upload the dragon text file
         uses: actions/upload-artifact@v4
         with:
            name: dragon-text-file
            path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download the dragon text file
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file

      - name: test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download the dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read File
        run: cat dragon.txt
      
      - name: Deploy
        run: echo Deploying ... 
   