name: Generate ASCII Artwork
on:
    push
jobs:
    ascii_job:
        name: My First Job
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: List Repo Files
              run: ls -ltra

            - name: Executing shell script
              run:  ./asci-script.sh
            
              