name: Exploring Variables and Secrets

on: 
    workflow_dispatch: #there should be a new button, which should be used
    #for manually triggering the workflows.
    #this will excute this workflow every minute
    #schedule:
     #   - cron: "*/1 * * * *"
    #push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }} /${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

            - name: Docker Login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}


