name: Exploring Variables and Secrets

on: 
    workflow_dispatch: # This enables the manual trigger button in the GitHub UI
    # Uncomment the schedule section if you want the workflow to run every minute
    # schedule:
    #   - cron: "*/1 * * * *"
    # push: # Uncomment this if you want the workflow to trigger on push events


concurrency:

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            - name: Docker Login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker publish
              run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy: 
        concurrency:
            group: production-deployment
            cancel-in-progress: true #any existing workflow that's running will be cancelled and run the new one
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: | 
            echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
            sleep 600s
#if we clicked the button 2 times the 2 jobs will run deployments concurrently
#concurrency ensures that only 1 job runs at a time.

